spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/spring-aws-lambda
    username: root
    password: 6548
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
