name: Setup API Gateway

on:
  workflow_run:
    workflows: ["Deploy Lambda Function"]
    types:
      - completed

jobs:
  setup_api_gateway:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      LAMBDA_FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}
      API_GATEWAY_NAME: ${{ secrets.API_GATEWAY_NAME }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      STAGE_NAME: "prod"
      OPENAPI_FILE: "openapi_base64.json"

    steps:
      # 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2

      # S3에서 OpenAPI 파일 다운로드
      - name: Download OpenAPI Spec from S3
        run: aws s3 cp s3://$S3_BUCKET_NAME/$OPENAPI_FILE .

      - name: Create or Update API Gateway
        id: setup_api_gateway
        run: |
          API_GATEWAY_ID=$(aws apigateway get-rest-apis --query "items[?name=='${API_GATEWAY_NAME}'].id" --output text --region $AWS_REGION)
          if [ -z "$API_GATEWAY_ID" ] || [ "$API_GATEWAY_ID" == "None" ]; then
            API_GATEWAY_ID=$(aws apigateway import-rest-api --body "file://${OPENAPI_FILE}" --query 'id' --output text --region $AWS_REGION)
          else
            aws apigateway put-rest-api --rest-api-id $API_GATEWAY_ID --mode overwrite --body "file://${OPENAPI_FILE}" --region $AWS_REGION
          fi

          aws apigateway update-rest-api --rest-api-id $API_GATEWAY_ID --patch-operations op=replace,path=/name,value="${API_GATEWAY_NAME}" --region $AWS_REGION
          echo "::set-output name=api_gateway_id::$API_GATEWAY_ID"

      - name: Deploy API Gateway
        run: |
          API_GATEWAY_ID=${{ steps.setup_api_gateway.outputs.api_gateway_id }}
          aws apigateway create-deployment --rest-api-id $API_GATEWAY_ID --stage-name $STAGE_NAME --region $AWS_REGION