name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1' # Change this to your region
        run: |
          aws s3 cp build/libs/your-app.jar s3://your-s3-bucket-name/your-app.jar

      - name: Check if Lambda Exists
        id: check_lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1' # Change this to your region
        run: |
          aws lambda get-function --function-name your-lambda-function-name || echo "Function does not exist"

      - name: Create or Update Lambda Function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1' # Change this to your region
        run: |
          if aws lambda get-function --function-name your-lambda-function-name; then
            aws lambda update-function-code --function-name your-lambda-function-name --s3-bucket your-s3-bucket-name --s3-key your-app.jar;
          else
            aws lambda create-function --function-name your-lambda-function-name --runtime java11 --role arn:aws:iam::123456789012:role/your-lambda-role --handler com.example.MyHandler::handleRequest --code S3Bucket=your-s3-bucket-name,S3Key=your-app.jar --description "My Java Lambda function" --timeout 15 --memory-size 512;
          fi
